title: "Dana"
description: >-
  Data Science Portfolio – Projects, Resume, and Skills.
show_downloads: true # or false to indicate whether to provide a download URL
# Theme
theme: jekyll-theme-minimal

logo: /assets/img/launch.png
# "C:\Users\USER\Desktop\resume2\assets\img\launch.png"
# favicon: /assets/img/favicon.ico
